kits/main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings


urlpatterns = patterns('kits.main.views',
    url(r'^$', 'home', name='home'),
    url(r'^about/$', 'about', name='about'),
    url(r'^how_to_install/$', 'how_to_install', name='how_to_install'),
    url(r'^faq/$', 'faq', name='faq'),
    url(r'^contacts/$', 'contacts', name='contacts'),
    url(r'^special_offer/$', 'special_offer', name='special_offer'),
    url(r'^feedback/$', 'feedback', name='feedback'),
)

kits/shop/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings


urlpatterns = patterns('kits.shop.views',
    url(r'^list/(?P<brand>[\w\-]+)/(?P<model>[\w\-]+)/$', 'car_list', name='car_list'),
    url(r'^sales/(?P<product>[\w\-]+)/$', 'hot_product', name='hot_product'),

    url(r'^cart/add/$', 'cart_add', name='cart_add'),
    url(r'^cart/delete/$', 'cart_delete', name='cart_delete'),
    url(r'^cart/show/$', 'cart_show', name='cart_show'),
    url(r'^cart/details/$', 'cart_details', name='cart_details'),
    url(r'^cart/refresh/$', 'cart_refresh', name='cart_refresh'),
    url(r'^cart/states/$', 'cart_states', name='cart_states'),

    url(r'^cart/$', 'cart', name='cart'),

    url(r'^admin/product/model/ajax/$', 'admin_model_filter', name='admin_model_filter'),

)

kits/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('kits.main.urls', 'main')),
    url(r'^shop/', include('kits.shop.urls','shop')),


    url(r'^redactor/', include('redactor.urls')),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
   )

kits/shop/models.py
# -*- coding: utf-8 -*-
from django.db import models
from redactor.fields import RedactorField

class Delivery(models.Model):
    title   = models.CharField(max_length=30, verbose_name=u'Название компании')
    url     = models.URLField(max_length=200, blank=True, verbose_name=u'Company url')
    price   = models.IntegerField(default=0, verbose_name=u'Цена')

    class Meta:
        verbose_name = u'shipping company'
        verbose_name_plural = u'Shipping companies'

    def __unicode__(self):
        return self.title


class Brand(models.Model):
    title = models.CharField(max_length=30, verbose_name=u'Brand name')
    slug = models.SlugField(max_length=30, verbose_name=u'Slug')
    class Meta:
        verbose_name = u'Brand'
        verbose_name_plural = u'Brands'

    @property
    def get_models(self):
        return Model.objects.filter(brand=self)

    def __unicode__(self):
        return self.title

class Model(models.Model):
    title = models.CharField(max_length=30, verbose_name=u'Model name')
    slug = models.SlugField(max_length=30, verbose_name=u'Slug')
    brand = models.ForeignKey(Brand, verbose_name=u'Brand')

    class Meta:
        verbose_name = u'Model'
        verbose_name_plural = u'Models'

    def __unicode__(self):
        return self.title

class Product(models.Model):
    title = models.CharField(max_length=30, verbose_name=u'Title')
    brand = models.ForeignKey(Brand, verbose_name= u'Brand',)
    model = models.ForeignKey(Model, verbose_name= u'Model')
    short_description = models.CharField(max_length=60, verbose_name= u'Short description')
    text = RedactorField(verbose_name=u'Text',)
    pub_date = models.DateTimeField(auto_now=True, auto_now_add=True, verbose_name=u'Pub date')
    price = models.DecimalField(default=0, verbose_name=u'Price', max_digits=8,decimal_places=2)
    preview = models.ImageField(verbose_name=u'Preview image', upload_to='products/', null = True)
    hot_sale=models.BooleanField(verbose_name=u'Hot sale')

    def get_product_images(self):
        return ProductImage.objects.filter(product=self)

    class Meta:
        verbose_name = u'Product'
        verbose_name_plural = u'Products'

    def __unicode__(self):
        return self.title


class ProductImage(models.Model):
    image = models.ImageField(verbose_name=u'Изображение', upload_to='products/', null = True, blank = True)
    product = models.ForeignKey(Product)

    class Meta:
        verbose_name = u'Image'
        verbose_name_plural = u'Imgaes'

    def __unicode__(self):
        return self.image

class Discount(models.Model):
    code =  models.CharField(max_length=30)
    discount =  models.IntegerField(default=0)


class Country(models.Model):
    name =  models.CharField(max_length=30)

    class Meta:
        verbose_name = u'Country'
        verbose_name_plural = u'Countries'

    def __unicode__(self):
        return self.name

class State(models.Model):
    name =  models.CharField(max_length=30)
    country = models.ForeignKey(Country)

    class Meta:
        verbose_name = u'State'
        verbose_name_plural = u'States'

    def __unicode__(self):
        return self.name

PAYMENT_CHOICES = (('1', 'Credit Card'),
                    ('2', 'Paypall'))


class Order(models.Model):
    delivery    = models.ForeignKey(Delivery, verbose_name= u'Delivery')
    discount    = models.CharField(max_length=30, verbose_name=u'Discount')
    payment     = models.CharField(max_length=20, verbose_name=u'Payment', choices=PAYMENT_CHOICES)
    first_name  = models.CharField(max_length=20, verbose_name=u'First name')
    middle_name = models.CharField(max_length=20, verbose_name=u'Middle name')
    last_name   = models.CharField(max_length=20, verbose_name=u'Last name')
    email       = models.CharField(max_length=20, verbose_name=u'Email')
    phone       = models.CharField(max_length=20, verbose_name=u'Telephone number')
    adress1     = models.CharField(max_length=20, verbose_name=u'Adress1')
    adress2     = models.CharField(max_length=20, blank=True, verbose_name=u'Adress2')
    city        = models.CharField(max_length=20, verbose_name=u'City')
    country     = models.ForeignKey(Country, verbose_name= u'Country')
    state       = models.ForeignKey(State, verbose_name= u'State')
    zipcode     = models.CharField(max_length=20, verbose_name=u'Zip Code')

kits/main/forms.py
# -*- coding: utf-8 -*-
from django import forms
from kits.main.models import Feedback

class FeedbackForm(forms.ModelForm):
	send_mail_copy = forms.BooleanField(required=False,initial=False,label='Send copy on my e-mail')
	class Meta:
		model = Feedback
		exclude = ('checked',)

kits/shop/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.conf import settings
from django.core.mail import EmailMessage
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _
from django.forms.formsets import formset_factory
from kits.shop.models import Order

class CartForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CartForm, self).__init__(*args, **kwargs)
        self.fields['delivery'].empty_label = None
        
    class Meta:
        model = Order
        widgets = {
            'delivery': forms.RadioSelect(),
        }

kits/main/views.py
# -*- coding: utf-8 -*-
from .. decorators import render_to, render_to_json
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.template import RequestContext
from django.http import Http404,HttpResponse
from django.shortcuts import render_to_response, HttpResponseRedirect, redirect
from django.core.urlresolvers import reverse
from django.core.mail import send_mail, BadHeaderError
from django.core import serializers
from kits.main.models import MainPage, AboutPage, HowToInstallPage, FaqPage, ConstactPage, SpecialOfferPage
from kits.main.forms import FeedbackForm

@render_to('main/home.html')
def home(request):
	page = MainPage.objects.get(pk=1)
	return {
		'page':page
	}

@render_to('main/about.html')
def about(request):
	page = AboutPage.objects.get(pk=1)
	return {
		'page':page
	}

@render_to('main/how_to_install.html')
def how_to_install(request):
	page = HowToInstallPage.objects.get(pk=1)
	return {
		'page':page
	}

@render_to('main/faq.html')
def faq(request):
	page = FaqPage.objects.get(pk=1)
	return {
		'page':page
	}

@render_to('main/contacts.html')
def contacts(request):
	page = ConstactPage.objects.get(pk=1)
	return {
		'page':page
	}

@render_to('main/special_offer.html')
def special_offer(request):
	page = SpecialOfferPage.objects.get(pk=1)
	return {
		'page':page
	}

@csrf_exempt
def feedback(request):
	form = FeedbackForm(request.POST or None)
	if form.is_valid():
		cd = form.cleaned_data
		obj = form.save()
		if cd['send_mail_copy']==True:
			subject = u"Feedback copy message"
			from_email = cd['email']
			message =''
			message += u"Name: %s \n\n" % cd['name']
			message += u"E-mail: %s \n\n" % cd['email']
			message += "Message:\n"
			message += cd['text']
			try:
				send_mail(subject, message, settings.EMAIL_HOST_USER, [from_email,])
			except BadHeaderError:
				raise Http404
		return HttpResponse("Feedback successfully send")
	return HttpResponse("Failed")

kits/shop/views.py
# -*- coding: utf-8 -*-
from .. decorators import render_to, render_to_json
from django.views.decorators.csrf import csrf_exempt

from django.template import RequestContext
from django.http import Http404,HttpResponse
from django.shortcuts import render_to_response, HttpResponseRedirect, redirect
from django.core.urlresolvers import reverse

from django.core import serializers

from kits.shop.models import Brand, Model, Product, Delivery, Discount, State
from kits.shop.forms import CartForm

from django.conf import settings

@render_to('shop/car_list.html')
def car_list(request,brand,model):
    products = Product.objects.filter(brand__slug=brand,model__slug=model).order_by('-pub_date')
    return {
        'products': products,
    }

@render_to('shop/hot_product.html')
def hot_product(request,product):
    product = Product.objects.get(id=product)
    return {
        'product': product,
    }

@render_to_json
def admin_model_filter(request):
    """
    Связные списки марка-модель в админке
    """
    data = {}
    if request.GET.get('brand'):
        brand_id = request.GET.get('brand')
        data = Model.objects.filter(brand=brand_id)
    data=serializers.serialize('json',data)
    return data



@render_to('shop/cart.html')
def cart(request):
    d = Delivery.objects.all()
    f = CartForm()

    if request.method == 'POST':
        f = CartForm(request.POST)
        if f.is_valid():
            print "VALID"
    return {
        'delivery': d,
        'CartForm': f,
    }


@csrf_exempt
@render_to_json
def cart_details(request):
    cart = request.session['cart']

    try:
        delivery = Delivery.objects.get(id=int(request.GET.get('delivery'))).price
    except (Delivery.DoesNotExist, ValueError):
        delivery = 0
    try:
        discount = Discount.objects.get(code=request.GET.get('discount')).discount
    except Discount.DoesNotExist:
        discount = 0
    res = {}
    res['count'] = cart['count']
    res['price'] = cart['price']
    res['delivery'] = delivery
    res['discount'] = discount
    res['cart'] = []

    for key in cart['cart'].keys():
        product = Product.objects.get(id = key)
        res['cart'].append({
            'id' : product.id, 
            'title' : product.title,
            'brand': str(product.brand),
            'model': str(product.model), 
            'price' : product.price, 
            'count' : cart['cart'][key]
            })
    return res    

@csrf_exempt
@render_to_json
def cart_add(request):
    cart = request.session['cart']
    if request.GET:
        id = request.GET.get('id')
        product = Product.objects.get(id = id)
        if cart['cart'].has_key(product.id):
            cart['cart'][product.id] += 1
        else:
            cart['cart'][product.id] = 1
        cart['count'] += 1
        cart['price'] += product.price
        request.session['cart'] = cart
        return {
            'count' : request.session['cart']['count'], 
            'price' : request.session['cart']['price']
        }
    else:
        return {}

@csrf_exempt
@render_to_json
def cart_show(request):
    if request.session.has_key('cart'):
        cart = request.session['cart']
        count = cart['count']
        price = cart['price']
        return {
            'count' : count, 
            'price' : price
        }
    else:
        request.session['cart'] = {
            'count' : 0,
            'price' : 0,
            'cart' : {}
        }
        return request.session['cart']


@csrf_exempt
@render_to_json
def cart_delete(request):
    cart = request.session['cart']
    if request.GET:
        id = request.GET.get('id')
        try:
            id = int(id)
            if cart['cart'].has_key(id):
                cart['count'] -= cart['cart'][id]
                cart['price'] -= cart['cart'][id] * Product.objects.get(id = id).price
                del cart['cart'][id]
        except:
            print "Item id not correctly"
    request.session['cart'] = cart


@csrf_exempt
@render_to_json
def cart_refresh(request):
    cart = request.session['cart']
    if request.GET:
        id = request.GET.get('id')
        count = request.GET.get('count')
        try:
            id = int(id)
            count = int(count)
        except:
            print "Id error"

        if cart['cart'].has_key(id):
            cart['count']-= cart['cart'][id]
            cart['price'] -= cart['cart'][id] * Product.objects.get(id = id).price
            cart['cart'][id] = count
            cart['count']+= count
            cart['price']+= count*Product.objects.get(id = id).price
    request.session['cart'] = cart
        


@csrf_exempt
@render_to_json
def cart_states(request):
    data = {}
    try:
        country_id = int(request.GET.get('country'))
    except ValueError:
        country_id = 0
    data = State.objects.filter(country=country_id)
    data=serializers.serialize('json',data)
    return data

kits/templates/shop/car_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load shop_widgets %}
{% load main_widgets %}
{% load thumbnail %}
{% block center_content %}
<div class="span7">
  {% if products %}
  {% for product in products %}
  <div class="row-fluid fone">
    <div class="span6 textCar">
      <h4>{{ product.title }}</h4>
      {{ product.text|safe }}
      <div class="redLine">
        <div class="allP">
          <p>{{ product.title }}</p>
          <p>{{ product.short_description }}</p>
        </div>
        <div class="redSale">${{ product.price }}</div>
      </div>
      <a class="btn silver" href="#" onclick="add_to_cart({{ product.id }})"><i class="icon-shopping-cart"></i> Add to car</a>
    </div>
    <div class="span6 photoCars">
      <div class="row">
        {% thumbnail product.preview "370x220" as im %}
            <img src="{{ im.url }}">
        {% endthumbnail %}
      </div>
      <div class="row-fluid">
        <div class="span12 miniFotoCar">
          {% for item in product.get_product_images %}
            {% thumbnail item.image "170x100" as im %}
              <img src="{{ im.url }}">
            {% endthumbnail %}
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  {% else %}
  <div class="row-fluid fone">
    <h4 class="text-center">Unfortunately this section is still empty.</h4>
  </div>
  {% endif %}         
</div>
{% endblock %}

kits/templates/shop/cart.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js %}
{{ block.super }}
<script type="text/javascript">
function select_linked(){
  $.ajax({
        url: '/shop/cart/states/?country='+$("#id_country").val(),
        type : "GET",
        dataType: "json",
        beforeSend: function () {
            $('#id_state').html('<option>Loading...</option>');
        },
        success: function (data) {
          var options = '<option value="">---------</option>';
          data= JSON.parse(data);
          for (x in data) {
              $(data[x].fields).each(function() {
                options += '<option value="' + $(data[x]).attr('pk') + '">' + $(this).attr('name') + '</option>';
              });
          }
          $('#id_state').html(options);
      }
  });
}

$(function() {
  $('#id_country').on('change', function() {
    select_linked();
  });
  $('#id_discount').on('change', function() {
    cart_details_load();
  });
  $('input[name=delivery]').click(function() {
    cart_details_load();
  });

  cart_details_load();//load cart list items onload
  select_linked();//load linked selects country/state
});
</script>
{% endblock %}

{% block center_content %}
<div class="span7 shopping">
  <h3>CHECKOUT</h3>
  <ul id="breadcrumbs-one">
    <li><a href="" class="active">Order Details</a></li>
    <li><a href="">Check details and pay</a></li>
    <li><a href="">Complete</a></li>
  </ul>
  <p class="smallItem" style="margin-top: 20px">Your ordered items:</p>
  <table class="tabels" cellpadding="5px" id="products-table">
    <tr>
      <td>Del</td>
      <td class="item">Item</td>
      <td class="carModel">Car model</td>
      <td class="quontity">Quontity</td>
      <td>Price</td>
    </tr>
  </table>
  <div class="row">
    <div class=" span4 discount">
      <p class="smallItem">Discount</p>
      {{ CartForm.discount }}<a class="btn">Use</a>
      <p><a href="#">Where I can get a discount?</a></p>
    </div>
    <div class=" span3 payment">
      <p class="smallItem" style="padding-left: 0px">Payment system</p>
      {{ CartForm.payment }}
    </div>
  </div>
  <div class="row">
    <div class="span4 shipping">
      <p class="smallItem">Shipping company</p>
      {% for radio in CartForm.delivery %}
        <p>{{ radio.tag }}<span>{{ radio.choice_label }}</span></p>
      {% endfor %}
    </div>
  </div>
  <div class="row personalInform">
    <div class="span4">
      <p class="smallItem">Your personal information:</p>
        <div class="form-horizontal">
          <div class="control-group">
            <label class="control-label">First Name</label>
            <div class="controls">{{ CartForm.first_name }}</div>
          </div>
          <div class="control-group">
            <label class="control-label">Middle Name</label>
            <div class="controls">{{ CartForm.middle_name }}</div>
          </div>
          <div class="control-group">
            <label class="control-label">Last Name</label>
            <div class="controls">{{ CartForm.last_name }}</div>
          </div>
          <div class="control-group">
            <label class="control-label">E-mail Address</label>
              <div class="controls">{{ CartForm.email }}</div>
          </div>
          <div class="control-group">
            <label class="control-label">Telephone number</label>
              <div class="controls">{{ CartForm.phone }}</div>
          </div>
        </div>
    </div>
    <div class="span3">
      <p>&nbsp;</p>
      <div class="form-horizontal">
        <div class="control-group">
          <label class="control-label">Address Line 1*:</label>
          <div class="controls">{{ CartForm.adress1 }}</div>
        </div>
        <div class="control-group">
          <label class="control-label">Address Line 2:</label>
          <div class="controls">{{ CartForm.adress2 }}</div>
        </div>
        <div class="control-group">
          <label class="control-label">Country:</label>
          <div class="controls">{{ CartForm.country }}</div>
        </div>
        <div class="control-group">
          <label class="control-label">State:</label>
          <div class="controls">{{ CartForm.state }}</div>
        </div>
        <div class="control-group">
          <label class="control-label">City:</label>
          <div class="controls">{{ CartForm.city }}</div>
        </div>
        <div class="control-group">
          <label class="control-label">Zip code:</label>
          <div class="controls">{{ CartForm.zipcode }}</div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="line span7" style="margin-left: 30px"></div>
  </div>
  <div class="row" style="margin-bottom: 40px">
    <div class="span7">
      <table class="lastTable">
        <tr><td>Total item cost:</td><td>$<span id="total_item_cost">00.00</span></td></tr>
        <tr><td>Total item discount:</td><td>$<span id="total_item_discount">00.00</span></td></tr>
        <tr><td>Total shipping:</td><td>$<span id="total_shipping">00.00</span></td>
        </tr><tr><td>Total cost:</td><td>$<span id="total_cost">00.00</span></td></tr>
      </table>
      <ul id="breadcrumbs-two">
        <li><a href="" style="padding-left: 2.6em;">Next step</a></li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

kits/templates/shop/hot_product.html
{% extends "base.html" %}
{% load staticfiles %}
{% load shop_widgets %}
{% load main_widgets %}
{% load thumbnail %}
{% block center_content %}
<div class="span7">
  <div class="row-fluid fone">
    <div class="span6 textCar">
      <h4>{{ product.title }}</h4>
      {{ product.text|safe }}
      <div class="redLine">
        <div class="allP">
          <p>{{ product.title }}</p>
          <p>{{ product.short_description }}</p>
        </div>
        <div class="redSale">${{ product.price }}</div>
      </div>
      <a class="btn silver" href="#" onclick="add_to_cart({{ product.id }})"><i class="icon-shopping-cart"></i> Add to car</a>
    </div>
    <div class="span6 photoCars">
      <div class="row">
        {% thumbnail product.preview "370x220" as im %}
            <img src="{{ im.url }}">
        {% endthumbnail %}
      </div>
      <div class="row-fluid">
        <div class="span12 miniFotoCar">
          {% for item in product.get_product_images %}
            {% thumbnail item.image "170x100" as im %}
              <img src="{{ im.url }}">
            {% endthumbnail %}
          {% endfor %}
        </div>
      </div>
    </div>
  </div>       
</div>
{% endblock %}